// Generated by build-voxels.mjs --swift from sites/apps/assets/voxel-models.json. Source SHA-256 f4f53444a20fe547fa328b08013217cbd010712b5a46349ad6827233596dc283. Do not edit.
import Foundation

/// Face palette key of one voxel; colors resolve through AIMMiniAppTokens in AIMVoxelView.swift.
public enum AIMVoxelColor: String, CaseIterable {
  case ink, mid, light, red
}

/// One finite reaction to a click, the same spec as aim-voxel.js: flash (cells take a colour for hold seconds and return),
/// mirror (the model mirrors on an axis and stays), cycle (the signal steps to the next cell of the list and stays).
public enum AIMVoxelGesture {
  case flash(cells: [(x: Int, y: Int, z: Int)], color: AIMVoxelColor, hold: Double)
  case mirror(axis: String)
  case cycle(cells: [(x: Int, y: Int, z: Int)], color: AIMVoxelColor)
}

/// Shared motion constants, seconds; web uses the same values in milliseconds.
public enum AIMVoxelMotion {
  public static let assemble: Double = 0.7
  public static let scatter: Double = 0.25
  public static let reassemble: Double = 0.55
  public static let hover: Double = 0.16
  public static let hoverLift: Double = 2
  public static let steps = (min: 6, max: 8)
}

/// One character: a light figure of at most 110 voxels in a 10×10×10 grid plus one gesture.
public struct AIMVoxelModel {
  public let name: String
  public let label: String
  public let note: String
  public let voxels: [(x: Int, y: Int, z: Int, c: AIMVoxelColor)]
  public let gesture: AIMVoxelGesture?
  public init(name: String, label: String, note: String, voxels: [(x: Int, y: Int, z: Int, c: AIMVoxelColor)], gesture: AIMVoxelGesture? = nil) {
    self.name = name; self.label = label; self.note = note; self.voxels = voxels; self.gesture = gesture
  }
  public var count: Int { voxels.count }
  /// Positions of the red signal voxels (one for relay, aside, calendar; a 2×2 block for family and prism).
  public var signals: [(x: Int, y: Int, z: Int)] { voxels.filter { $0.c == .red }.map { ($0.x, $0.y, $0.z) } }
}

public enum AIMVoxelModels {
  public static let version = "2026-09-14"
  public static let sourceSHA256 = "f4f53444a20fe547fa328b08013217cbd010712b5a46349ad6827233596dc283"
  public static let grid = (x: 10, y: 10, z: 10)
  public static let unit: Double = 10
  public static let projection = "screen = (ox + (x - y) * u, oy + (x + y) * 0.48 * u - z * u)"

  /// ai mindset · family profile · 29 voxels
  public static let family = AIMVoxelModel(name: "family", label: "ai mindset · family profile", note: "one-sheet head ring with air inside, 2×2 red eye, three-cube smile, two-cube stem", voxels: [
    (1, 5, 4, .ink), (2, 5, 3, .ink), (3, 5, 2, .ink), (5, 5, 0, .ink), (1, 5, 5, .ink), (4, 5, 2, .ink),
    (5, 5, 1, .ink), (1, 5, 6, .ink), (4, 5, 3, .mid), (5, 5, 2, .ink), (1, 5, 7, .ink), (5, 5, 3, .mid),
    (6, 5, 2, .ink), (3, 5, 6, .red), (2, 5, 8, .ink), (3, 5, 7, .red), (4, 5, 6, .red), (6, 5, 4, .mid),
    (7, 5, 3, .ink), (4, 5, 7, .red), (3, 5, 9, .ink), (8, 5, 4, .ink), (4, 5, 9, .ink), (8, 5, 5, .ink),
    (5, 5, 9, .ink), (8, 5, 6, .ink), (6, 5, 9, .ink), (7, 5, 8, .ink), (8, 5, 7, .ink)
  ], gesture: .flash(cells: [(3, 5, 6), (4, 5, 6), (3, 5, 7), (4, 5, 7)], color: .light, hold: 0.14))

  /// language relay · 36 voxels
  public static let relay = AIMVoxelModel(name: "relay", label: "language relay", note: "two light arrows, two sheets deep, red tip on the outgoing one", voxels: [
    (1, 5, 1, .ink), (1, 6, 1, .ink), (2, 5, 1, .mid), (3, 5, 0, .mid), (2, 6, 1, .mid), (3, 5, 1, .mid),
    (3, 6, 0, .mid), (3, 5, 2, .mid), (3, 6, 1, .mid), (4, 5, 1, .mid), (1, 5, 5, .mid), (3, 6, 2, .mid),
    (4, 6, 1, .mid), (5, 5, 1, .mid), (1, 6, 5, .mid), (2, 5, 5, .mid), (5, 6, 1, .mid), (6, 5, 1, .mid),
    (2, 6, 5, .mid), (3, 5, 5, .mid), (6, 6, 1, .mid), (7, 5, 1, .mid), (3, 6, 5, .mid), (4, 5, 5, .mid),
    (7, 6, 1, .mid), (4, 6, 5, .mid), (5, 5, 5, .mid), (6, 5, 4, .mid), (5, 6, 5, .mid), (6, 5, 5, .mid),
    (6, 6, 4, .mid), (6, 5, 6, .mid), (6, 6, 5, .mid), (7, 5, 5, .mid), (6, 6, 6, .mid), (7, 6, 5, .red)
  ], gesture: .mirror(axis: "z"))

  /// aside tweaks · 46 voxels
  public static let aside = AIMVoxelModel(name: "aside", label: "aside tweaks", note: "panel frame (no plate), three light row sticks, red cursor at the first row", voxels: [
    (0, 5, 0, .mid), (0, 5, 1, .mid), (1, 5, 0, .mid), (0, 5, 2, .mid), (2, 5, 0, .mid), (0, 5, 3, .mid),
    (3, 5, 0, .mid), (0, 5, 4, .mid), (2, 5, 2, .light), (4, 5, 0, .mid), (0, 5, 5, .mid), (3, 5, 2, .light),
    (5, 5, 0, .mid), (0, 5, 6, .mid), (2, 5, 4, .light), (4, 5, 2, .light), (6, 5, 0, .mid), (0, 5, 7, .mid),
    (3, 5, 4, .light), (5, 5, 2, .light), (7, 5, 0, .mid), (0, 5, 8, .mid), (2, 5, 6, .red), (4, 5, 4, .light),
    (8, 5, 0, .mid), (1, 5, 8, .mid), (3, 5, 6, .light), (5, 5, 4, .light), (8, 5, 1, .mid), (2, 5, 8, .mid),
    (4, 5, 6, .light), (6, 5, 4, .light), (8, 5, 2, .mid), (3, 5, 8, .mid), (5, 5, 6, .light), (8, 5, 3, .mid),
    (4, 5, 8, .mid), (6, 5, 6, .light), (8, 5, 4, .mid), (5, 5, 8, .mid), (8, 5, 5, .mid), (6, 5, 8, .mid),
    (8, 5, 6, .mid), (7, 5, 8, .mid), (8, 5, 7, .mid), (8, 5, 8, .mid)
  ], gesture: .cycle(cells: [(2, 5, 6), (2, 5, 4), (2, 5, 2)], color: .red))

  /// mem prism · 64 voxels
  public static let prism = AIMVoxelModel(name: "prism", label: "mem prism", note: "hollow 4×4 crystal, height 7, mid corner columns, 2×2 red heart seen through the front notch", voxels: [
    (3, 3, 1, .mid), (3, 3, 2, .mid), (3, 4, 1, .light), (4, 3, 1, .light), (4, 4, 0, .ink), (3, 3, 3, .mid),
    (3, 4, 2, .light), (4, 3, 2, .light), (3, 5, 1, .light), (5, 3, 1, .light), (4, 5, 0, .ink), (5, 4, 0, .ink),
    (3, 3, 4, .mid), (3, 4, 3, .light), (4, 3, 3, .light), (3, 5, 2, .light), (5, 3, 2, .light), (3, 6, 1, .mid),
    (6, 3, 1, .mid), (5, 5, 0, .ink), (3, 3, 5, .mid), (3, 4, 4, .light), (4, 3, 4, .light), (3, 5, 3, .light),
    (4, 4, 3, .red), (5, 3, 3, .light), (3, 6, 2, .mid), (6, 3, 2, .mid), (4, 6, 1, .light), (6, 4, 1, .light),
    (3, 4, 5, .light), (4, 3, 5, .light), (3, 5, 4, .light), (5, 3, 4, .light), (3, 6, 3, .mid), (4, 5, 3, .red),
    (5, 4, 3, .red), (6, 3, 3, .mid), (4, 6, 2, .light), (6, 4, 2, .light), (5, 6, 1, .light), (6, 5, 1, .light),
    (3, 5, 5, .light), (5, 3, 5, .light), (3, 6, 4, .mid), (6, 3, 4, .mid), (4, 6, 3, .light), (5, 5, 3, .red),
    (6, 4, 3, .light), (5, 6, 2, .light), (6, 5, 2, .light), (6, 6, 1, .mid), (4, 4, 6, .mid), (3, 6, 5, .mid),
    (6, 3, 5, .mid), (4, 6, 4, .light), (6, 4, 4, .light), (4, 5, 6, .mid), (5, 4, 6, .mid), (4, 6, 5, .light),
    (6, 4, 5, .light), (5, 5, 6, .mid), (5, 6, 5, .light), (6, 5, 5, .light)
  ], gesture: .flash(cells: [(6, 4, 3), (6, 4, 4), (4, 6, 3), (4, 6, 4), (6, 5, 2), (5, 6, 2), (6, 5, 5), (5, 6, 5), (6, 6, 1)], color: .red, hold: 0.16))

  /// calendar control · 29 voxels
  public static let calendar = AIMVoxelModel(name: "calendar", label: "calendar control", note: "ink header row, five-by-four day grid with one-cell gaps, red today", voxels: [
    (0, 5, 0, .mid), (0, 5, 2, .mid), (2, 5, 0, .mid), (0, 5, 4, .mid), (2, 5, 2, .mid), (4, 5, 0, .mid),
    (0, 5, 6, .mid), (2, 5, 4, .mid), (4, 5, 2, .mid), (6, 5, 0, .mid), (0, 5, 8, .ink), (2, 5, 6, .mid),
    (4, 5, 4, .red), (6, 5, 2, .mid), (8, 5, 0, .mid), (1, 5, 8, .ink), (2, 5, 8, .ink), (4, 5, 6, .mid),
    (6, 5, 4, .mid), (8, 5, 2, .mid), (3, 5, 8, .ink), (4, 5, 8, .ink), (6, 5, 6, .mid), (8, 5, 4, .mid),
    (5, 5, 8, .ink), (6, 5, 8, .ink), (8, 5, 6, .mid), (7, 5, 8, .ink), (8, 5, 8, .ink)
  ], gesture: .cycle(cells: [(4, 5, 4), (6, 5, 4), (4, 5, 4), (2, 5, 4)], color: .red))

  /// Catalog order: family, relay, aside, prism, calendar.
  public static let all: [AIMVoxelModel] = [family, relay, aside, prism, calendar]
  public static func model(named name: String) -> AIMVoxelModel? { all.first { $0.name == name } }
}
